version: "3.8"

services:
  database:
    container_name: database
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://database:27017/nucba_mern
    depends_on:
      - database
volumes:
  mongo-data:
    driver: local
